version: "2"

services:
  libs:
    build: services/libs
  eventstore:
    build: services/eventstore-service
    ports:
      - 28888:28888
    restart: always
  unary:
    build: services/node-unary-service
    links:
      - eventstore
  server-stream:
    build: services/node-server-streaming-service
    links:
    - eventstore