version: "2"

services:
  libs:
    build: services/libs
  eventstore:
    build: services/eventstore-service
    ports:
      - 28888:28888
    restart: always
  user:
    build: services/user-service
    links:
    - eventstore
    ports:
      - 8081:8081
    restart: always
  view:
    build: services/view-service
    links:
    - eventstore:eventstore
    ports:
    - 8082:8082
    restart: always